// src/views/Setting/index.vue
<!-- 全局设置 -->
<template>
  <div :class="{ setting: true, 'use-cover': themeAutoCover }">
    <n-h1 class="title">
      <n-text>全局设置</n-text>
      <div class="copyright">
        <n-text class="version" depth="3">{{ packageJson.version }}</n-text>
      </div>
    </n-h1>
    <!-- 导航栏 -->
    <n-tabs ref="setTabsRef" v-model:value="setTabsValue" type="segment" @update:value="settingTabChange">
      <n-tab name="setTab1"> 常规 </n-tab>
      <n-tab name="setTab2"> 播放 </n-tab>
      <n-tab name="setTab3"> 歌词 </n-tab>
      <n-tab name="setTab4"> 其他 </n-tab>
    </n-tabs>
    <!-- 设置项 -->
    <n-scrollbar ref="setScrollRef" :style="{
      height: `calc(100vh - ${music.getPlaySongData?.id && showPlayBar ? 328 : 248}px)`,
    }" class="all-set" @scroll="allSetScroll">
      <!-- 常规 -->
      <div class="set-type">
        <n-h3 prefix="bar"> 常规 </n-h3>
        <n-card class="set-item">
          <div class="name">明暗模式</div>
          <n-select v-model:value="themeType" :options="[
            {
              label: '浅色模式',
              value: 'light',
            },
            {
              label: '深色模式',
              value: 'dark',
            },
          ]" class="set" @update:value="(themeAuto = false)" />
        </n-card>
        <n-card class="set-item">
          <div class="name">明暗模式是否跟随系统</div>
          <n-switch v-model:value="themeAuto" :round="false" @update:value="
            (val) => {
              if (val) themeType = osThemeRef;
            }
          " />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            开启侧边栏
            <n-text class="tip">将导航栏放于侧边显示，可展开或收起</n-text>
          </div>
          <n-switch v-model:value="showSider" :round="false" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            侧边栏展示封面
            <n-text class="tip">侧边栏歌单是否展示歌单封面</n-text>
          </div>
          <n-switch v-model:value="siderShowCover" :disabled="!showSider" :round="false" />
        </n-card>
        <n-card class="set-item">
          <div class="name">显示搜索历史</div>
          <n-switch v-model:value="showSearchHistory" :round="false" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            页面字体
            <n-text class="tip">全局界面显示的字体</n-text>
          </div>
          <n-select v-model:value="siteFont" :options="fontOptions" class="set" @update:value="updateSiteFont" />
        </n-card>
        <n-card class="set-item">
          <div class="name">主题选择</div>
          <n-select v-model:value="themeTypeName" :options="Object.values(themeColorData)" class="set" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            <div class="dev">
              全局动态取色
              <n-tag :bordered="false" round size="small" type="warning">
                开发中
                <template #icon>
                  <n-icon>
                    <SvgIcon icon="code" />
                  </n-icon>
                </template>
              </n-tag>
            </div>
            <n-text class="tip">主题色是否跟随封面，目前感觉不好看</n-text>
          </div>
          <n-switch v-model:value="themeAutoCover" :round="false" :disabled="Object.keys(coverTheme)?.length === 0"
            @update:value="themeAutoCoverChange" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            <div class="dev">
              全局动态取色类别
              <n-tag :bordered="false" round size="small" type="warning">
                开发中
                <template #icon>
                  <n-icon>
                    <SvgIcon icon="code" />
                  </n-icon>
                </template>
              </n-tag>
            </div>
            <n-text class="tip">将在下一首播放或刷新时生效，不建议更改</n-text>
          </div>
          <n-select v-model:value="themeAutoCoverType" :disabled="!themeAutoCover" :options="[
            {
              label: '中性',
              value: 'neutral',
            },
            {
              label: '中性变体',
              value: 'neutralVariant',
            },
            {
              label: '主要',
              value: 'primary',
            },
            {
              label: '次要',
              value: 'secondary',
            },
            {
              label: '次次要',
              value: 'tertiary',
            },
          ]" class="set" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            SessionID
            <n-text class="tip">{{ sessionId }}</n-text>
          </div>
          <n-button strong secondary type="default" @click="copySessionId"> 复制 </n-button>
        </n-card>
      </div>
      <!-- 播放 -->
      <div class="set-type">
        <n-h3 prefix="bar"> 播放 </n-h3>
        <n-card class="set-item">
          <div class="name">
            在线播放音质
            <n-text class="tip">
              {{ songLevelData[songLevel].tip }}
            </n-text>
          </div>
          <n-select v-model:value="songLevel" :options="Object.values(songLevelData)" class="set" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            使用 HTML5 播放器
            <n-text class="tip"> 如果开启，则会使用 Audio 标签播放音频，支持动态加载，但在 Safari 浏览器上可能会遇到进度不同步问题；<br>如果关闭，则会使用 Web Audio API 播放音频，播放需缓存整个音频文件，暂停音乐会导致 Media Session 媒体会话被清除，无法恢复播放。<br>切换该开关后最好刷新页面。 </n-text>
          </div>
          <n-switch v-model:value="html5Player" :round="false" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            静音模拟播放
            <n-text class="tip"> 不请求音乐文件，但是模拟时间轴以显示歌词，以及上报播放数据 </n-text>
          </div>
          <n-switch v-model:value="simulationPlaying" :round="false" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            自动播放
            <n-text class="tip">自动播放上次歌曲</n-text>
          </div>
          <n-switch v-model:value="autoPlay" :round="false" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            记忆上次播放位置
            <n-text v-if="autoPlay" class="tip"> 与自动播放相冲突，已禁用 </n-text>
          </div>
          <n-switch v-model:value="memorySeek" :disabled="autoPlay" :round="false" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            音乐资源自动缓存
            <n-text class="tip"> 可能会造成加载缓慢，将在下一首播放或刷新时生效 </n-text>
          </div>
          <n-switch v-model:value="useMusicCache" :round="false" />
        </n-card>
        <n-card class="set-item">
          <div class="name">音乐渐入渐出</div>
          <n-switch v-model:value="songVolumeFade" :round="false" />
        </n-card>
        <n-card class="set-item" :content-style="{
          flexDirection: 'column',
          alignItems: 'flex-start',
        }">
          <div class="name">
            一起听歌同步阈值
            <n-text class="tip">本地播放时间与服务器播放时间差值超过该设定时自动同步进度</n-text>
            <n-text class="tip"> {{ listenTogetherSyncThreshold }} ms </n-text>
          </div>
          <n-slider v-model:value="listenTogetherSyncThreshold" :tooltip="false" :max="2000" :min="100" :step="50" :marks="{
            100: '极小',
            300: '默认',
            1000: '1000ms',
            2000: '2000ms',
          }" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            播放全部搜索歌曲
            <n-text class="tip">
              在播放搜索页面上的歌曲时，是否同时播放所有搜索结果中的歌曲
            </n-text>
          </div>
          <n-switch v-model:value="playSearch" :round="false" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            底栏歌词显示
            <n-text class="tip">是否在播放时将歌手信息更改为歌词</n-text>
          </div>
          <n-switch v-model:value="bottomLyricShow" :round="false" />
        </n-card>
        <n-card class="set-item">
          <div class="name">显示播放列表歌曲数量</div>
          <n-switch v-model:value="showPlaylistCount" :round="false" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            播放器样式
            <n-text class="tip"> 播放器左侧区域样式 </n-text>
          </div>
          <n-select v-model:value="playCoverType" :options="[
            {
              label: '封面模式',
              value: 'cover',
            },
            {
              label: '唱片模式',
              value: 'record',
            },
          ]" class="set" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            播放背景样式
            <n-text class="tip">
              {{
                playerBackgroundType === "animation"
                  ? "流体效果，较消耗性能，请谨慎开启"
                  : playerBackgroundType === "blur"
                    ? "将封面模糊处理为背景"
                    : "提取封面主色为渐变色"
              }}
            </n-text>
          </div>
          <n-select v-model:value="playerBackgroundType" :options="[
            {
              label: '流体效果',
              value: 'animation',
            },
            {
              label: '封面模糊',
              value: 'blur',
            },
            {
              label: '主色渐变',
              value: 'gradient',
            },
            {
              label: 'AMLL 流体效果',
              value: 'amllAnimation',
            },
          ]" class="set" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            显示前奏倒计时
            <n-text class="tip">部分歌曲前奏可能存在显示错误</n-text>
          </div>
          <n-switch v-model:value="countDownShow" :round="false" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            <div class="dev">
              显示音乐频谱
              <n-tag :bordered="false" round size="small" type="warning">
                开发中
                <template #icon>
                  <n-icon>
                    <SvgIcon icon="code" />
                  </n-icon>
                </template>
              </n-tag>
            </div>
            <n-text class="tip">
              {{
                showSpectrums
                  ? "开启音乐频谱会极大影响性能，如遇问题请关闭"
                  : "是否在播放器底部显示音乐频谱"
              }}
            </n-text>
          </div>
          <n-switch v-model:value="showSpectrums" :round="false" />
        </n-card>
      </div>
      <!-- 歌词 -->
      <div class="set-type">
        <n-h3 prefix="bar"> 歌词 </n-h3>
        <n-card class="set-item" :content-style="{
          flexDirection: 'column',
          alignItems: 'flex-start',
        }">
          <div class="name">
            歌词文本大小
            <n-text :style="{ fontSize: lyricsFontSize + 'px', fontWeight: 'bold' }" class="tip">
              我是一句歌词
            </n-text>
          </div>
          <n-slider v-model:value="lyricsFontSize" :tooltip="false" :max="56" :min="36" :step="1" :marks="{
            36: '最小',
            46: '默认',
            56: '最大',
          }" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            歌词显示字体
            <n-text class="tip">播放页展示歌词所使用的字体</n-text>
          </div>
          <n-select v-model:value="lyricFont" :options="fontOptions" class="set" @update:value="updateLyricFont" />
        </n-card>
        <n-card class="set-item" :content-style="{
          flexDirection: 'column',
          alignItems: 'flex-start',
        }">
          <div class="name">
            歌词偏转
            <n-text class="tip">使歌词提前切到下一行，用于抵消歌词步进延迟</n-text>
            <n-text class="tip">
              {{ lyricsOffset }} s
            </n-text>
          </div>
          <n-slider v-model:value="lyricsOffset" :tooltip="false" :max="3" :min="0" :step="0.01" :marks="{
            0: '无',
            0.4: '默认',
            3: '最大',
          }" />
        </n-card>
        <n-card class="set-item" :content-style="{
          flexDirection: 'column',
          alignItems: 'flex-start',
        }">
          <div class="name">
            Hook 歌词偏转
            <n-text class="tip">window.$MeTMusic_Data 中歌词计算的偏移量，用于桌面歌词等外部场景</n-text>
            <n-text class="tip">
              {{ lyricsHookOffset }} s
            </n-text>
          </div>
          <n-slider v-model:value="lyricsHookOffset" :tooltip="false" :max="3" :min="0" :step="0.01" :marks="{
            0: '无',
            0.3: '默认',
            3: '最大',
          }" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            智能暂停滚动
            <n-text class="tip">鼠标移入歌词区域是否暂停滚动</n-text>
          </div>
          <n-switch v-model:value="lrcMousePause" :round="false" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            歌词位置
            <n-text class="tip">歌词的默认垂直位置</n-text>
          </div>
          <n-select v-model:value="lyricsPosition" :options="[
            {
              label: '居左',
              value: 'left',
            },
            {
              label: '居中',
              value: 'center',
            },
            {
              label: '居右',
              value: 'right',
            },
          ]" class="set" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            歌词滚动位置
            <n-text class="tip">歌词高亮时所处的位置</n-text>
          </div>
          <n-select v-model:value="lyricsBlock" :options="[
            {
              label: '靠近顶部',
              value: 'start',
            },
            {
              label: '水平居中',
              value: 'center',
            },
          ]" class="set" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            <div class="dev">
              是否去除歌曲信息
            </div>
            <n-text class="tip">去除歌词最前面的版权信息</n-text>
          </div>
          <n-switch v-model:value="removeInfo" :round="false" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            <div class="dev">
              显示逐字歌词
              <n-tag :bordered="false" round size="small" type="warning">
                开发中
                <template #icon>
                  <n-icon>
                    <SvgIcon icon="code" />
                  </n-icon>
                </template>
              </n-tag>
            </div>
            <n-text class="tip">是否在具有逐字歌词时显示</n-text>
          </div>
          <n-switch v-model:value="showYrc" :round="false" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            <div class="dev">
              显示逐字歌词动画
              <n-tag :bordered="false" round size="small" type="warning">
                开发中
                <template #icon>
                  <n-icon>
                    <SvgIcon icon="code" />
                  </n-icon>
                </template>
              </n-tag>
            </div>
            <n-text class="tip">可能会造成卡顿等性能问题，建议显卡为 GTX 2060 及以上</n-text>
          </div>
          <n-switch v-model:value="showYrcAnimation" :disabled="!showYrc" :round="false" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            显示歌词翻译
            <n-text class="tip">是否在具有翻译歌词时显示</n-text>
          </div>
          <n-switch v-model:value="showTransl" :round="false" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            显示歌词音译
            <n-text class="tip">是否在具有音译歌词时显示</n-text>
          </div>
          <n-switch v-model:value="showRoma" :round="false" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            歌词自动聚焦
            <n-text class="tip">是否聚焦显示当前播放行，其他行将模糊显示</n-text>
          </div>
          <n-switch v-model:value="lyricsBlur" :round="false" />
        </n-card>

        <n-card class="set-item">
          <div class="name">
            <div class="dev">
              使用 Apple Music-like Lyrics
            </div>
            <n-text class="tip">歌词使用 Apple Music-like Lyrics 进行渲染，需要高性能设备</n-text>
          </div>
          <n-switch v-model:value="useAMLyrics" :round="false" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            <div class="dev">
              Apple Music-like Lyrics 歌词弹簧效果
            </div>
            <n-text class="tip">是否使用物理弹簧算法实现歌词动画效果，需要高性能设备</n-text>
          </div>
          <n-switch v-model:value="useAMSpring" :round="false" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            <div class="dev">
              Apple Music-like Lyrics 歌词缩放效果
            </div>
            <n-text class="tip">放大高亮行歌词，需要高性能设备</n-text>
          </div>
          <n-switch v-model:value="useAMScale" :round="false" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            <div class="dev">
              Apple Music-like Lyrics 去除歌词信息
            </div>
            <n-text class="tip">去除 AM 歌词最前面的版权信息</n-text>
          </div>
          <n-switch v-model:value="removeAMInfo" :round="false" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            <div class="dev">
              Apple Music-like Lyrics 使用社区动效歌词
            </div>
            <n-text class="tip">使用 Steve-xmh/amll-ttml-db 的社区动效歌词库</n-text>
          </div>
          <n-switch v-model:value="useAMttmlDB" :round="false" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            <div class="dev">
              Apple Music-like Lyrics 对 TMLL 歌词使用偏转
            </div>
            <n-text class="tip">不推荐开启，TMLL已对歌词进行过优化</n-text>
          </div>
          <n-switch v-model:value="lyricsAMttmlUseOffset" :round="false" />
        </n-card>
        <n-card class="set-item" :content-style="{
          flexDirection: 'column',
          alignItems: 'flex-start',
        }">
          <div class="name">
            Apple Music-like Lyrics 歌词偏转
            <n-text class="tip">用于抵消歌词动画产生的延迟</n-text>
            <n-text class="tip">
              {{ lyricsAMOffset }} ms
            </n-text>
          </div>
          <n-slider v-model:value="lyricsAMOffset" :tooltip="false" :max="2000" :min="0" :step="1" :marks="{
            0: '无',
            150: '默认',
            2000: '最大',
          }" />
        </n-card>
        <n-card class="set-item" :content-style="{
          flexDirection: 'column',
          alignItems: 'flex-start',
        }">
          <div class="name">
            Apple Music-like Lyrics 歌词切行偏转
            <n-text class="tip">使歌词提前切到下一行，仅对非 TTML 歌词有效</n-text>
            <n-text class="tip"> {{ lyricsAMEndTimeOffset }} ms </n-text>
          </div>
          <n-slider v-model:value="lyricsAMEndTimeOffset" :tooltip="false" :max="2000" :min="0" :step="1" :marks="{
            0: '无',
            250: '默认',
            2000: '最大',
          }" />
        </n-card>
        <n-card class="set-item" :content-style="{
          flexDirection: 'column',
          alignItems: 'flex-start',
        }">
          <div class="name">
            Apple Music-like Lyrics 背景流动速度
            <n-text class="tip">可以设置 AMLL 歌词背景流动速度</n-text>
            <n-text class="tip">
              {{ amllPlayerBackgroundFlowSpeed }}
            </n-text>
          </div>
          <n-slider v-model:value="amllPlayerBackgroundFlowSpeed" :tooltip="false" :max="10" :min="1" :step="1" :marks="{
            1: '最小',
            2: '默认',
            10: '最大',
          }" />
        </n-card>
      </div>
      <!-- 其他 -->
      <div class="set-type">
        <n-h3 prefix="bar"> 其他 </n-h3>
        <n-card class="set-item">
          <div class="name">
            默认加载数量
            <n-text class="tip">在部分列表页面显示几条数据</n-text>
          </div>
          <n-select v-model:value="loadSize" :options="[
            {
              label: '少一点（ 30 条 ）',
              value: 30,
            },
            {
              label: '差不多刚刚好（ 50 条 ）',
              value: 50,
            },
            {
              label: '我要很多（ 100 条 ）',
              value: 100,
            },
          ]" class="set" @update:value="themeAuto = false" />
        </n-card>
        <n-card class="set-item">
          <div class="name">
            程序重置
            <n-text class="tip">若程序显示异常或出现问题时可尝试此操作</n-text>
          </div>
          <n-button strong secondary type="error" @click="resetApp"> 重置 </n-button>
        </n-card>
      </div>
    </n-scrollbar>
  </div>
</template>

<script setup>
import { inject } from "vue";
import { storeToRefs } from "pinia";
import { useOsTheme } from "naive-ui";
import { siteSettings, siteStatus, musicData } from "@/stores";
import { getSessionId } from "@/utils/helper";
import debounce from "@/utils/debounce";
// import themeColorData from "@/assets/themeColor.json";
import packageJson from "@/../package.json";

const music = musicData();
const status = siteStatus();
const settings = siteSettings();
const { showPlayBar, coverTheme } = storeToRefs(status);
const {
  themeType,
  themeTypeName,
  themeAuto,
  themeAutoCover,
  themeAutoCoverType,
  showSider,
  loadSize,
  songVolumeFade,
  autoPlay,
  showYrc,
  showYrcAnimation,
  countDownShow,
  playerBackgroundType,
  showTransl,
  showRoma,
  songLevel,
  lyricsPosition,
  lyricsBlock,
  lrcMousePause,
  lyricsFontSize,
  lyricsBlur,
  showSearchHistory,
  bottomLyricShow,
  memorySeek,
  playCoverType,
  playSearch,
  showPlaylistCount,
  showSpectrums,
  siderShowCover,
  useMusicCache,
  removeInfo,
  lyricsOffset,
  lyricsAMOffset,
  useAMLyrics,
  useAMSpring,
  useAMScale,
  removeAMInfo,
  useAMttmlDB,
  lyricsAMttmlUseOffset,
  lyricsAMEndTimeOffset,
  simulationPlaying,
  amllPlayerBackgroundFlowSpeed,
  lyricsHookOffset,
  siteFont,
  lyricFont,
  html5Player,
  listenTogetherSyncThreshold,
} = storeToRefs(settings);

const updateLyricFont = inject("updateLyricFont");
const updateSiteFont = inject("updateSiteFont");

// 标签页数据
// const setTabsRef = ref(null);
// const setScrollRef = ref(null);
const setTabsValue = ref("setTab1");

// 基础数据
const osThemeRef = useOsTheme();
const sessionId = getSessionId();

// 音质数据
const songLevelData = {
  web: {
    label: "普通 WEB",
    tip: "在线流媒体音质",
    value: "web",
  },
  hq: {
    label: "极高 HQ",
    tip: "近 CD 品质的细节体验，最高 320kbps",
    value: "hq",
  },
  sq: {
    label: "无损 SQ",
    tip: "高保真无损音质，最高 48kHz/24bit",
    value: "sq",
  },
  rs: {
    label: "高分辨率音源 Hi-Res",
    tip: "索尼高品质音乐标准，高于 44.1kHz/16bit",
    value: "rs",
  },
  dts: {
    label: "杜比 5.1 声道",
    tip: "六声道环绕声，使人产生犹如身临音乐厅的感觉",
    value: "dts",
  },
  q360v1: {
    label: "臻品全景声 V1",
    tip: "独家自研空间音频，V1 版本，立体声",
    value: "q360v1",
  },
  q360v2: {
    label: "臻品全景声 V2",
    tip: "独家自研空间音频，V2 版本，多声道",
    value: "q360v2",
  },
  qai: {
    label: "臻品母带",
    tip: "还原声音细节，让声音还原更加极致",
    value: "qai",
  },
};

// 主题数据
const themeColorData = {
  red: {
    label: "欢快派对",
    value: "red",
  },
  orange: {
    label: "柑橘桔梦",
    value: "orange",
  },
  blue: {
    label: "深海蓝梦",
    value: "blue",
  },
  pink: {
    label: "粉色梦幻",
    value: "pink",
  },
  brown: {
    label: "深棕林荫",
    value: "brown",
  },
  indigo: {
    label: "星空靛蓝",
    value: "indigo",
  },
  green: {
    label: "生命绿洲",
    value: "green",
  },
  purple: {
    label: "皇室紫梦",
    value: "purple",
  },
  yellow: {
    label: "金色阳光",
    value: "yellow",
  },
  teal: {
    label: "海洋碧绿",
    value: "teal",
  }
};

// 字体选项
const fontOptions = [
  { label: 'HarmonyOS Regular', value: 'harmony_reg' },
  { label: 'HarmonyOS Bold', value: 'harmony_bold' },
  { label: 'PingFangSC Regular', value: 'pingfang_reg' },
  { label: 'PingFangSC Semibold', value: 'pingfang_semi' },
  { label: '系统默认', value: 'system' },
];


// 封面自动跟随变化
const themeAutoCoverChange = (val) => {
  if ($changeThemeColor !== "undefined" && Object.keys(coverTheme.value)?.length) {
    $changeThemeColor(val ? coverTheme.value : themeTypeName.value, val);
  }
};

// 标签页切换
const settingTabChange = (name) => {
  const index = Number(name.replace("setTab", ""));
  const setDom = document.querySelectorAll(".set-type")?.[index - 1];
  if (!setDom) return false;
  // 滚动至设置分类
  setDom.scrollIntoView({ behavior: "smooth" });
};

// 设置列表滚动
const allSetScroll = debounce((e) => {
  const distance = e.target.scrollTop + 30;
  const allSetDom = document.querySelectorAll(".set-type");
  allSetDom.forEach((v, i) => {
    if (distance >= v.offsetTop) setTabsValue.value = `setTab${i + 1}`;
  });
}, 100);

// 程序重置
const resetApp = () => {
  $dialog.warning({
    title: "程序重置",
    content: "确认重置为默认状态？你的登录状态以及自定义设置都将丢失！",
    positiveText: "重置",
    negativeText: "取消",
    onPositiveClick: () => {
      if (typeof $cleanAll === "undefined") {
        return $message.error("重置操作出现错误，请重试");
      }
      $cleanAll(false);
      $message.success("重置成功，正在重启");
      setTimeout(() => {
        window.location.href = "/";
      }, 1000);
    },
  });
};

// 复制 Session ID
const copySessionId = async () => {
  try {
    if (window?.electron?.clipboard) {
      // Electron 环境
      electron.clipboard.writeText(sessionId);
    } else if (navigator.clipboard?.writeText) {
      // 浏览器环境
      await navigator.clipboard.writeText(sessionId);
    } else {
      // Fallback：旧浏览器或不支持 navigator.clipboard
      const textarea = document.createElement("textarea");
      textarea.value = sessionId;
      textarea.style.position = "fixed";
      textarea.style.opacity = "0";
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
    }

    $message.success("已复制 Session ID 到剪贴板");
  } catch (err) {
    console.error("复制 Session ID 失败：", err);
    $message.error("复制失败");
  }
};

</script>

<style lang="scss" scoped>
.setting {
  max-width: 1200px;
  margin: 0 auto;

  .title {
    display: flex;
    flex-direction: row;
    align-items: flex-end;
    height: 58px;
    margin: 20px 0;
    font-size: 36px;
    font-weight: bold;

    .copyright {
      display: flex;
      flex-direction: row;
      align-items: center;
      margin-left: 12px;
      margin-bottom: 6px;
      font-size: 16px;
      font-weight: normal;
      cursor: pointer;

      .author {
        display: flex;
        align-items: center;

        &::after {
          content: "/";
          transform: translateY(2px);
          font-size: 14px;
          margin: 0 6px;
          opacity: 0.6;
        }

        .author-text {
          margin-left: 6px;
        }
      }

      .version {
        &::before {
          content: "v";
          margin-right: 2px;
        }
      }
    }
  }

  .n-tabs {
    height: 42px;
  }

  .set-type {
    padding-top: 30px;

    .set-item {
      width: 100%;
      border-radius: 8px;
      margin-bottom: 12px;

      &:last-child {
        margin-bottom: 0;
      }

      :deep(.n-card__content) {
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: space-between;
      }

      .name {
        font-size: 16px;
        display: flex;
        flex-direction: column;
        padding-right: 20px;

        .dev {
          display: flex;
          flex-direction: row;
          align-items: center;

          .n-tag {
            margin-left: 6px;
          }
        }

        .tip {
          font-size: 12px;
          opacity: 0.8;
        }
      }

      .set {
        width: 200px;

        @media (max-width: 768px) {
          width: 140px;
          min-width: 140px;
        }
      }
    }
  }

  &.use-cover {
    .n-switch {
      &.n-switch--active {
        :deep(.n-switch__rail) {
          background-color: var(--main-second-color);
        }
      }
    }
  }
}
</style>

// packages/app/src/pages/Setting.tsx
/**
 * 全局设置(旧 src/views/Setting/index.vue 的 React 移植,U3 阶段)。
 * 所有设置项直接读写 useSettingsStore(setState 即自动持久化,引擎实时读取)。
 */
import { useRef, useState } from "react";
import { toast } from "sonner";
import { useSettingsStore } from "@/stores/settings";
import { useStatusStore } from "@/stores/status";
import { useHostStore } from "@/host";
import { cleanAll, getSessionId } from "@/platform/web";
import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { Select } from "@/components/ui/select";
import { Slider } from "@/components/ui/slider";
import { Switch } from "@/components/ui/switch";
import { SettingItem, SettingSection, SliderMarks } from "./setting/SettingItem";
import {
  closeTypeOptions,
  fontOptions,
  loadSizeOptions,
  lyricsBlockOptions,
  lyricsPositionOptions,
  playCoverTypeOptions,
  playerBackgroundTypeOptions,
  searchLoadSizeOptions,
  songLevelData,
  songLevelOptions,
  themeAutoCoverTypeOptions,
  themeColorOptions,
  themeTypeOptions,
} from "./setting/options";
import packageJson from "../../package.json";

const set = useSettingsStore.setState;

/** 分区导航(点击滚动至对应分组) */
const sections = ["常规", "桌面客户端", "播放", "歌词", "其他"] as const;
type SectionName = (typeof sections)[number];

const Setting = () => {
  const settings = useSettingsStore();
  const coverTheme = useStatusStore((s) => s.coverTheme);
  const isHosted = useHostStore((s) => s.isHosted);

  const [activeTab, setActiveTab] = useState<SectionName>("常规");
  const [resetOpen, setResetOpen] = useState(false);
  const sectionRefs = useRef<Partial<Record<SectionName, HTMLDivElement | null>>>({});

  const sessionId = getSessionId();

  // 明暗模式切换(对齐旧 setThemeType:setState + toast + 关闭跟随系统)
  const changeThemeType = (value: "light" | "dark") => {
    if (value === settings.themeType && !settings.themeAuto) return;
    set({ themeType: value, themeAuto: false });
    toast(`已切换至${value === "light" ? "浅色" : "深色"}模式`);
  };

  // 明暗模式跟随系统(开启时同步为系统主题,对齐旧页 osThemeRef)
  const changeThemeAuto = (value: boolean) => {
    if (value) {
      const osTheme = window.matchMedia("(prefers-color-scheme: dark)").matches
        ? "dark"
        : "light";
      set({ themeAuto: true, themeType: osTheme });
    } else {
      set({ themeAuto: false });
    }
  };

  // 复制 Session ID(对齐旧 copySessionId,浏览器剪贴板 + 旧浏览器兜底)
  const copySessionId = async () => {
    try {
      if (navigator.clipboard?.writeText) {
        await navigator.clipboard.writeText(sessionId);
      } else {
        const textarea = document.createElement("textarea");
        textarea.value = sessionId;
        textarea.style.position = "fixed";
        textarea.style.opacity = "0";
        document.body.appendChild(textarea);
        textarea.select();
        document.execCommand("copy");
        document.body.removeChild(textarea);
      }
      toast.success("已复制 Session ID 到剪贴板");
    } catch (err) {
      console.error("复制 Session ID 失败：", err);
      toast.error("复制失败");
    }
  };

  // 程序重置(Dialog 二次确认后执行,对齐旧 resetApp)
  const confirmReset = () => {
    setResetOpen(false);
    cleanAll(false);
    toast.success("重置成功，正在重启");
    setTimeout(() => {
      window.location.href = "/";
    }, 1000);
  };

  // 分区跳转
  const scrollToSection = (name: SectionName) => {
    setActiveTab(name);
    sectionRefs.current[name]?.scrollIntoView({ behavior: "smooth", block: "start" });
  };

  const bindSection = (name: SectionName) => (el: HTMLDivElement | null) => {
    sectionRefs.current[name] = el;
  };

  return (
    <div className="mx-auto max-w-5xl px-8 py-8">
      {/* 标题(对齐旧页:标题 + 版本号) */}
      <div className="mb-5 flex items-end gap-3">
        <h1 className="text-3xl font-bold text-[var(--met-fg)]">全局设置</h1>
        <span className="pb-1 text-sm text-[var(--met-fg-dim)]">v{packageJson.version}</span>
      </div>

      {/* 分区导航 */}
      <div className="sticky top-0 z-10 -mx-2 mb-2 flex gap-1 rounded-xl bg-[var(--met-bg-elevated)] p-1">
        {sections.map((name) => (
          <button
            key={name}
            type="button"
            onClick={() => scrollToSection(name)}
            className={`flex-1 cursor-pointer rounded-lg px-3 py-1.5 text-sm transition-colors ${
              activeTab === name
                ? "bg-[var(--met-bg-hover)] text-[var(--met-fg)]"
                : "text-[var(--met-fg-dim)] hover:text-[var(--met-fg)]"
            }`}
          >
            {name}
          </button>
        ))}
      </div>

      {/* 常规 */}
      <div ref={bindSection("常规")}>
        <SettingSection title="常规">
          <SettingItem name="明暗模式">
            <Select
              value={settings.themeType}
              options={themeTypeOptions}
              onValueChange={changeThemeType}
              className="w-52"
            />
          </SettingItem>
          <SettingItem name="明暗模式是否跟随系统">
            <Switch checked={settings.themeAuto} onCheckedChange={changeThemeAuto} />
          </SettingItem>
          <SettingItem name="开启侧边栏" tip="将导航栏放于侧边显示，可展开或收起">
            <Switch
              checked={settings.showSider}
              onCheckedChange={(v) => set({ showSider: v })}
            />
          </SettingItem>
          <SettingItem name="侧边栏展示封面" tip="侧边栏歌单是否展示歌单封面">
            <Switch
              checked={settings.siderShowCover}
              disabled={!settings.showSider}
              onCheckedChange={(v) => set({ siderShowCover: v })}
            />
          </SettingItem>
          <SettingItem name="显示搜索历史">
            <Switch
              checked={settings.showSearchHistory}
              onCheckedChange={(v) => set({ showSearchHistory: v })}
            />
          </SettingItem>
          <SettingItem name="页面字体" tip="全局界面显示的字体">
            <Select
              value={settings.siteFont}
              options={fontOptions}
              onValueChange={(v) => set({ siteFont: v })}
              className="w-52"
            />
          </SettingItem>
          <SettingItem name="主题选择">
            <Select
              value={settings.themeTypeName}
              options={themeColorOptions}
              onValueChange={(v) => set({ themeTypeName: v })}
              className="w-52"
            />
          </SettingItem>
          <SettingItem name="全局动态取色" dev tip="主题色是否跟随封面，目前感觉不好看">
            <Switch
              checked={settings.themeAutoCover}
              disabled={Object.keys(coverTheme).length === 0}
              onCheckedChange={(v) => set({ themeAutoCover: v })}
            />
          </SettingItem>
          <SettingItem name="全局动态取色类别" dev tip="将在下一首播放或刷新时生效，不建议更改">
            <Select
              value={settings.themeAutoCoverType}
              options={themeAutoCoverTypeOptions}
              disabled={!settings.themeAutoCover}
              onValueChange={(v) => set({ themeAutoCoverType: v })}
              className="w-52"
            />
          </SettingItem>
          <SettingItem name="SessionID" tip={sessionId}>
            <Button variant="outline" onClick={copySessionId}>
              复制
            </Button>
          </SettingItem>
        </SettingSection>
      </div>

      {/* 桌面客户端(Electron 专属,浏览器中置灰展示) */}
      <div ref={bindSection("桌面客户端")}>
        <SettingSection title="桌面客户端" note={isHosted ? undefined : "桌面客户端生效"}>
          <SettingItem name="关闭软件提醒弹窗" tip="关闭软件时是否弹窗询问" dimmed={!isHosted}>
            <Switch
              checked={settings.closeTip}
              disabled={!isHosted}
              onCheckedChange={(v) => set({ closeTip: v })}
            />
          </SettingItem>
          <SettingItem name="关闭软件方式" tip="点击关闭按钮时的默认行为" dimmed={!isHosted}>
            <Select
              value={settings.closeType}
              options={closeTypeOptions}
              disabled={!isHosted}
              onValueChange={(v) => set({ closeType: v })}
              className="w-52"
            />
          </SettingItem>
          <SettingItem name="显示歌曲任务栏进度" tip="在任务栏图标上显示播放进度" dimmed={!isHosted}>
            <Switch
              checked={settings.showTaskbarProgress}
              disabled={!isHosted}
              onCheckedChange={(v) => set({ showTaskbarProgress: v })}
            />
          </SettingItem>
        </SettingSection>
      </div>

      {/* 播放 */}
      <div ref={bindSection("播放")}>
        <SettingSection title="播放">
          <SettingItem
            name="在线播放音质"
            tip={songLevelData[settings.songLevel]?.tip ?? ""}
          >
            <Select
              value={settings.songLevel}
              options={songLevelOptions}
              onValueChange={(v) => set({ songLevel: v })}
              className="w-52"
            />
          </SettingItem>
          <SettingItem
            name="使用 HTML5 播放器"
            tip={
              <>
                <span className="block">
                  如果开启，则会使用 Audio 标签播放音频，支持动态加载，但在 Safari
                  浏览器上可能会遇到进度不同步问题；
                </span>
                <span className="block">
                  如果关闭，则会使用 Web Audio API 播放音频，播放需缓存整个音频文件，暂停音乐会导致
                  Media Session 媒体会话被清除，无法恢复播放。
                </span>
                <span className="block">切换该开关后最好刷新页面。</span>
              </>
            }
          >
            <Switch
              checked={settings.html5Player}
              onCheckedChange={(v) => set({ html5Player: v })}
            />
          </SettingItem>
          <SettingItem
            name="静音模拟播放"
            tip="不请求音乐文件，但是模拟时间轴以显示歌词，以及上报播放数据"
          >
            <Switch
              checked={settings.simulationPlaying}
              onCheckedChange={(v) => set({ simulationPlaying: v })}
            />
          </SettingItem>
          <SettingItem name="自动播放" tip="自动播放上次歌曲">
            <Switch checked={settings.autoPlay} onCheckedChange={(v) => set({ autoPlay: v })} />
          </SettingItem>
          <SettingItem
            name="记忆上次播放位置"
            tip={settings.autoPlay ? "与自动播放相冲突，已禁用" : undefined}
          >
            <Switch
              checked={settings.memorySeek}
              disabled={settings.autoPlay}
              onCheckedChange={(v) => set({ memorySeek: v })}
            />
          </SettingItem>
          <SettingItem
            name="音乐资源自动缓存"
            tip="可能会造成加载缓慢，将在下一首播放或刷新时生效"
          >
            <Switch
              checked={settings.useMusicCache}
              onCheckedChange={(v) => set({ useMusicCache: v })}
            />
          </SettingItem>
          <SettingItem name="音乐渐入渐出">
            <Switch
              checked={settings.songVolumeFade}
              onCheckedChange={(v) => set({ songVolumeFade: v })}
            />
          </SettingItem>
          <SettingItem
            name="一起听歌同步阈值"
            column
            tip={
              <>
                <span className="block">
                  本地播放时间与服务器播放时间差值超过该设定时自动同步进度
                </span>
                <span className="block">{settings.listenTogetherSyncThreshold} ms</span>
              </>
            }
          >
            <Slider
              value={settings.listenTogetherSyncThreshold}
              min={100}
              max={2000}
              step={50}
              onValueChange={(v) => set({ listenTogetherSyncThreshold: v })}
            />
            <SliderMarks marks={["极小", "2000ms"]} />
          </SettingItem>
          <SettingItem
            name="播放全部搜索歌曲"
            tip="在播放搜索页面上的歌曲时，是否同时播放所有搜索结果中的歌曲"
          >
            <Switch
              checked={settings.playSearch}
              onCheckedChange={(v) => set({ playSearch: v })}
            />
          </SettingItem>
          <SettingItem name="底栏歌词显示" tip="是否在播放时将歌手信息更改为歌词">
            <Switch
              checked={settings.bottomLyricShow}
              onCheckedChange={(v) => set({ bottomLyricShow: v })}
            />
          </SettingItem>
          <SettingItem name="显示播放列表歌曲数量">
            <Switch
              checked={settings.showPlaylistCount}
              onCheckedChange={(v) => set({ showPlaylistCount: v })}
            />
          </SettingItem>
          <SettingItem name="播放器样式" tip="播放器左侧区域样式">
            <Select
              value={settings.playCoverType}
              options={playCoverTypeOptions}
              onValueChange={(v) => set({ playCoverType: v })}
              className="w-52"
            />
          </SettingItem>
          <SettingItem
            name="播放背景样式"
            tip={
              settings.playerBackgroundType === "animation"
                ? "流体效果，较消耗性能，请谨慎开启"
                : settings.playerBackgroundType === "blur"
                  ? "将封面模糊处理为背景"
                  : "提取封面主色为渐变色"
            }
          >
            <Select
              value={settings.playerBackgroundType}
              options={playerBackgroundTypeOptions}
              onValueChange={(v) => set({ playerBackgroundType: v })}
              className="w-52"
            />
          </SettingItem>
          <SettingItem name="显示前奏倒计时" tip="部分歌曲前奏可能存在显示错误">
            <Switch
              checked={settings.countDownShow}
              onCheckedChange={(v) => set({ countDownShow: v })}
            />
          </SettingItem>
          <SettingItem
            name="显示音乐频谱"
            dev
            tip={
              settings.showSpectrums
                ? "开启音乐频谱会极大影响性能，如遇问题请关闭"
                : "是否在播放器底部显示音乐频谱"
            }
          >
            <Switch
              checked={settings.showSpectrums}
              onCheckedChange={(v) => set({ showSpectrums: v })}
            />
          </SettingItem>
        </SettingSection>
      </div>

      {/* 歌词 */}
      <div ref={bindSection("歌词")}>
        <SettingSection title="歌词">
          <SettingItem
            name="歌词文本大小"
            column
            tip={
              <span
                className="font-bold text-[var(--met-fg)]"
                style={{ fontSize: `${settings.lyricsFontSize}px` }}
              >
                我是一句歌词
              </span>
            }
          >
            <Slider
              value={settings.lyricsFontSize}
              min={36}
              max={56}
              step={1}
              onValueChange={(v) => set({ lyricsFontSize: v })}
            />
            <SliderMarks marks={["最小", "默认 46", "最大"]} />
          </SettingItem>
          <SettingItem name="歌词显示字体" tip="播放页展示歌词所使用的字体">
            <Select
              value={settings.lyricFont}
              options={fontOptions}
              onValueChange={(v) => set({ lyricFont: v })}
              className="w-52"
            />
          </SettingItem>
          <SettingItem
            name="歌词偏转"
            column
            tip={
              <>
                <span className="block">使歌词提前切到下一行，用于抵消歌词步进延迟</span>
                <span className="block">{settings.lyricsOffset} s</span>
              </>
            }
          >
            <Slider
              value={settings.lyricsOffset}
              min={0}
              max={3}
              step={0.01}
              onValueChange={(v) => set({ lyricsOffset: Math.round(v * 100) / 100 })}
            />
            <SliderMarks marks={["无", "默认 0.4", "最大"]} />
          </SettingItem>
          <SettingItem
            name="Hook 歌词偏转"
            column
            tip={
              <>
                <span className="block">
                  window.$MeTMusic_Data 中歌词计算的偏移量，用于桌面歌词等外部场景
                </span>
                <span className="block">{settings.lyricsHookOffset} s</span>
              </>
            }
          >
            <Slider
              value={settings.lyricsHookOffset}
              min={0}
              max={3}
              step={0.01}
              onValueChange={(v) => set({ lyricsHookOffset: Math.round(v * 100) / 100 })}
            />
            <SliderMarks marks={["无", "默认 0.3", "最大"]} />
          </SettingItem>
          <SettingItem name="智能暂停滚动" tip="鼠标移入歌词区域是否暂停滚动">
            <Switch
              checked={settings.lrcMousePause}
              onCheckedChange={(v) => set({ lrcMousePause: v })}
            />
          </SettingItem>
          <SettingItem name="歌词位置" tip="歌词的默认垂直位置">
            <Select
              value={settings.lyricsPosition}
              options={lyricsPositionOptions}
              onValueChange={(v) => set({ lyricsPosition: v })}
              className="w-52"
            />
          </SettingItem>
          <SettingItem name="歌词滚动位置" tip="歌词高亮时所处的位置">
            <Select
              value={settings.lyricsBlock}
              options={lyricsBlockOptions}
              onValueChange={(v) => set({ lyricsBlock: v })}
              className="w-52"
            />
          </SettingItem>
          <SettingItem name="是否去除歌曲信息" tip="去除歌词最前面的版权信息">
            <Switch
              checked={settings.removeInfo}
              onCheckedChange={(v) => set({ removeInfo: v })}
            />
          </SettingItem>
          <SettingItem name="显示逐字歌词" dev tip="是否在具有逐字歌词时显示">
            <Switch checked={settings.showYrc} onCheckedChange={(v) => set({ showYrc: v })} />
          </SettingItem>
          <SettingItem
            name="显示逐字歌词动画"
            dev
            tip="可能会造成卡顿等性能问题，建议显卡为 GTX 2060 及以上"
          >
            <Switch
              checked={settings.showYrcAnimation}
              disabled={!settings.showYrc}
              onCheckedChange={(v) => set({ showYrcAnimation: v })}
            />
          </SettingItem>
          <SettingItem name="显示歌词翻译" tip="是否在具有翻译歌词时显示">
            <Switch
              checked={settings.showTransl}
              onCheckedChange={(v) => set({ showTransl: v })}
            />
          </SettingItem>
          <SettingItem name="显示歌词音译" tip="是否在具有音译歌词时显示">
            <Switch checked={settings.showRoma} onCheckedChange={(v) => set({ showRoma: v })} />
          </SettingItem>
          <SettingItem name="歌词自动聚焦" tip="是否聚焦显示当前播放行，其他行将模糊显示">
            <Switch
              checked={settings.lyricsBlur}
              onCheckedChange={(v) => set({ lyricsBlur: v })}
            />
          </SettingItem>
          <SettingItem
            name="使用 Apple Music-like Lyrics"
            tip="歌词使用 Apple Music-like Lyrics 进行渲染，需要高性能设备"
          >
            <Switch
              checked={settings.useAMLyrics}
              onCheckedChange={(v) => set({ useAMLyrics: v })}
            />
          </SettingItem>
          <SettingItem
            name="Apple Music-like Lyrics 歌词弹簧效果"
            tip="是否使用物理弹簧算法实现歌词动画效果，需要高性能设备"
          >
            <Switch
              checked={settings.useAMSpring}
              onCheckedChange={(v) => set({ useAMSpring: v })}
            />
          </SettingItem>
          <SettingItem
            name="Apple Music-like Lyrics 歌词缩放效果"
            tip="放大高亮行歌词，需要高性能设备"
          >
            <Switch
              checked={settings.useAMScale}
              onCheckedChange={(v) => set({ useAMScale: v })}
            />
          </SettingItem>
          <SettingItem
            name="Apple Music-like Lyrics 去除歌词信息"
            tip="去除 AM 歌词最前面的版权信息"
          >
            <Switch
              checked={settings.removeAMInfo}
              onCheckedChange={(v) => set({ removeAMInfo: v })}
            />
          </SettingItem>
          <SettingItem
            name="Apple Music-like Lyrics 使用社区动效歌词"
            tip="使用 Steve-xmh/amll-ttml-db 的社区动效歌词库"
          >
            <Switch
              checked={settings.useAMttmlDB}
              onCheckedChange={(v) => set({ useAMttmlDB: v })}
            />
          </SettingItem>
          <SettingItem
            name="Apple Music-like Lyrics 对 TMLL 歌词使用偏转"
            tip="不推荐开启，TMLL已对歌词进行过优化"
          >
            <Switch
              checked={settings.lyricsAMttmlUseOffset}
              onCheckedChange={(v) => set({ lyricsAMttmlUseOffset: v })}
            />
          </SettingItem>
          <SettingItem
            name="Apple Music-like Lyrics 歌词偏转"
            column
            tip={
              <>
                <span className="block">用于抵消歌词动画产生的延迟</span>
                <span className="block">{settings.lyricsAMOffset} ms</span>
              </>
            }
          >
            <Slider
              value={settings.lyricsAMOffset}
              min={0}
              max={2000}
              step={1}
              onValueChange={(v) => set({ lyricsAMOffset: v })}
            />
            <SliderMarks marks={["无", "默认 150", "最大"]} />
          </SettingItem>
          <SettingItem
            name="Apple Music-like Lyrics 歌词切行偏转"
            column
            tip={
              <>
                <span className="block">使歌词提前切到下一行，仅对非 TTML 歌词有效</span>
                <span className="block">{settings.lyricsAMEndTimeOffset} ms</span>
              </>
            }
          >
            <Slider
              value={settings.lyricsAMEndTimeOffset}
              min={0}
              max={2000}
              step={1}
              onValueChange={(v) => set({ lyricsAMEndTimeOffset: v })}
            />
            <SliderMarks marks={["无", "默认 250", "最大"]} />
          </SettingItem>
          <SettingItem
            name="Apple Music-like Lyrics 背景流动速度"
            column
            tip={
              <>
                <span className="block">可以设置 AMLL 歌词背景流动速度</span>
                <span className="block">{settings.amllPlayerBackgroundFlowSpeed}</span>
              </>
            }
          >
            <Slider
              value={settings.amllPlayerBackgroundFlowSpeed}
              min={1}
              max={10}
              step={1}
              onValueChange={(v) => set({ amllPlayerBackgroundFlowSpeed: v })}
            />
            <SliderMarks marks={["最小", "默认 2", "最大"]} />
          </SettingItem>
        </SettingSection>
      </div>

      {/* 其他 */}
      <div ref={bindSection("其他")}>
        <SettingSection title="其他">
          <SettingItem name="默认加载数量" tip="在部分列表页面显示几条数据">
            <Select
              value={String(settings.loadSize)}
              options={loadSizeOptions}
              onValueChange={(v) => set({ loadSize: Number(v) })}
              className="w-52"
            />
          </SettingItem>
          <SettingItem name="搜索结果加载数量" tip="搜索结果每页加载几条数据">
            <Select
              value={String(settings.searchLoadSize)}
              options={searchLoadSizeOptions}
              onValueChange={(v) => set({ searchLoadSize: Number(v) })}
              className="w-52"
            />
          </SettingItem>
        </SettingSection>
      </div>

      {/* 关于 */}
      <SettingSection title="关于">
        <SettingItem name="版本" tip="MeT-Music">
          <span className="text-sm text-[var(--met-fg-dim)]">v{packageJson.version}</span>
        </SettingItem>
        <SettingItem name="程序重置" tip="若程序显示异常或出现问题时可尝试此操作">
          <Button variant="danger" onClick={() => setResetOpen(true)}>
            重置
          </Button>
        </SettingItem>
      </SettingSection>

      {/* 程序重置确认弹窗(对齐旧 $dialog.warning) */}
      <Dialog
        open={resetOpen}
        onOpenChange={setResetOpen}
        title="程序重置"
        footer={
          <>
            <Button variant="ghost" onClick={() => setResetOpen(false)}>
              取消
            </Button>
            <Button variant="danger" onClick={confirmReset}>
              重置
            </Button>
          </>
        }
      >
        确认重置为默认状态？你的登录状态以及自定义设置都将丢失！
      </Dialog>
    </div>
  );
};

export default Setting;
