// packages/app/src/pages/list/Playlist.tsx
import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { useSearch } from "@tanstack/react-router";
import { List, Play } from "lucide-react";
import { api, formatNumber, getTimestampTime, playAllSongs, type Song } from "@met/core";
import formatData, { getCoverUrl } from "@/lib/formatData";
import SongList from "@/components/list/SongList";
import { DropdownMenu, type MenuItemDef } from "@/components/ui/menu";
import { getAssetUrl } from "@/platform/web";
import { useSiteDataStore } from "@/stores/siteData";
import { useStatusStore } from "@/stores/status";

/** 创建者头像地址(对照旧 playlist.vue:追加规格参数并升级 https) */
const creatorAvatarUrl = (avatarUrl: unknown): string => {
  if (typeof avatarUrl !== "string" || !avatarUrl) {
    return getAssetUrl("/images/pic/avatar.jpg");
  }
  return `${avatarUrl}?param=300y300`.replace(/^http:/, "https:");
};

/** 超大歌单阈值与分片大小(对照旧 playlist.vue getBigPlayListData:>=800 触发,每片 800) */
const BIG_LIST_THRESHOLD = 800;
const BIG_LIST_CHUNK = 800;

/** 歌单详情页(id 来自 search params;/like-songs 复用本组件,无 id 时依赖登录态) */
export default function Playlist() {
  const search = useSearch({ strict: false }) as { id?: number | string };
  const id = search.id;
  const [keyword, setKeyword] = useState("");
  const isInRoom = useStatusStore((s) => s.isInRoom);
  const userLoginStatus = useSiteDataStore((s) => s.userLoginStatus);
  const userPlaylists = useSiteDataStore((s) => s.userLikeData.playlists) as {
    id?: number | string;
  }[];

  // like-songs 形态(无 id):已登录时取「我喜欢」歌单
  // (对照旧 playlist.vue:userLikeData.playlists[0]?.id)
  const likeSongsId = userLoginStatus ? (userPlaylists[0]?.id ?? null) : null;
  const playlistId = id != null && id !== "" ? id : likeSongsId;
  const enabled = playlistId != null && playlistId !== "";

  // 歌单详情(名称/简介/封面/歌曲数)
  const detailQuery = useQuery({
    queryKey: ["playlist", "detail", playlistId],
    queryFn: () => api.getPlayListDetail(playlistId as number | string),
    enabled,
  });

  const detail = detailQuery.data?.playlist;
  const trackCount = Number(detail?.trackCount) || 0;

  // 超大歌单分片加载进度(null = 非分片加载或已完成)
  const [bigListProgress, setBigListProgress] = useState<{
    loaded: number;
    total: number;
  } | null>(null);

  // 歌单全部歌曲:trackCount >= 800 时分片循环拉全量(对照旧 getBigPlayListData)
  const songsQuery = useQuery({
    queryKey: ["playlist", "songs", playlistId, trackCount],
    enabled: enabled && detailQuery.isSuccess,
    queryFn: async () => {
      if (trackCount < BIG_LIST_THRESHOLD) {
        return api.getAllPlayList(playlistId as number | string, trackCount || 500, 0);
      }
      // 分片循环拉取并聚合
      const allSongs: unknown[] = [];
      setBigListProgress({ loaded: 0, total: trackCount });
      try {
        let offset = 0;
        while (offset < trackCount) {
          const res = await api.getAllPlayList(
            playlistId as number | string,
            BIG_LIST_CHUNK,
            offset,
          );
          const chunk: unknown[] = Array.isArray(res?.songs) ? res.songs : [];
          allSongs.push(...chunk);
          offset += BIG_LIST_CHUNK;
          setBigListProgress({
            loaded: Math.min(allSongs.length, trackCount),
            total: trackCount,
          });
          // 后端提前见底,防止死循环
          if (chunk.length === 0) break;
        }
      } finally {
        setBigListProgress(null);
      }
      return { songs: allSongs };
    },
  });

  const songs = useMemo<Song[]>(
    () => formatData(songsQuery.data?.songs, "song") ?? [],
    [songsQuery.data],
  );

  // 更多操作(对照旧 playlist.vue moreOptions)
  const moreOptions: MenuItemDef[] = [
    {
      key: "open-source",
      label: "打开源页面链接",
      onSelect: () => {
        if (playlistId != null) window.open(`https://y.qq.com/n/ryqq/playlist/${playlistId}`);
      },
    },
    {
      key: "open-classic",
      label: "打开经典播放器",
      onSelect: () => {
        if (playlistId != null) window.open(`/classic/player/?tid=${playlistId}`);
      },
    },
  ];

  if (!enabled) {
    // like-songs 形态(路由无 id):未登录时不发请求,提示登录
    if (!userLoginStatus) {
      return (
        <div className="flex h-full min-h-[320px] flex-col items-center justify-center gap-2">
          <p className="text-lg font-medium text-[var(--met-fg)]">请登录后使用</p>
          <p className="text-sm text-[var(--met-fg-dim)]">
            登录账号后即可查看「我喜欢的音乐」歌单
          </p>
        </div>
      );
    }
    // 已登录但用户歌单尚未就绪(setUserProfile 可能仍在拉取)
    return (
      <div className="py-24 text-center text-sm text-[var(--met-fg-dim)]">
        正在获取「我喜欢的音乐」歌单…
      </div>
    );
  }

  if (detailQuery.isError) {
    return (
      <div className="py-24 text-center text-sm text-[var(--met-fg-dim)]">
        歌单加载失败,请稍后重试
      </div>
    );
  }

  return (
    <div className="mx-auto flex w-full max-w-5xl flex-col px-4 py-6">
      {/* 头部信息 */}
      {detailQuery.isLoading || !detail ? (
        <div className="flex animate-pulse gap-5">
          <div className="h-40 w-40 shrink-0 rounded-xl bg-[var(--met-bg-elevated)]" />
          <div className="flex flex-1 flex-col justify-center gap-3">
            <div className="h-5 w-1/3 rounded bg-[var(--met-bg-elevated)]" />
            <div className="h-3 w-2/3 rounded bg-[var(--met-bg-elevated)]" />
            <div className="h-3 w-1/4 rounded bg-[var(--met-bg-elevated)]" />
          </div>
        </div>
      ) : (
        <div className="flex gap-5">
          <img
            src={getCoverUrl(detail.coverImgUrl, 300)}
            alt=""
            className="h-40 w-40 shrink-0 rounded-xl bg-[var(--met-bg-elevated)] object-cover"
          />
          <div className="flex min-w-0 flex-1 flex-col justify-center gap-2">
            <h1 className="truncate text-2xl font-semibold text-[var(--met-fg)]" title={detail.name}>
              {detail.name}
            </h1>
            {/* 创建者(对照旧 .creator:头像 / 昵称 / 创建时间) */}
            {detail.creator || detail.createTime ? (
              <div className="flex items-center gap-2">
                <img
                  src={creatorAvatarUrl(detail.creator?.avatarUrl)}
                  alt=""
                  loading="lazy"
                  onError={(e) => {
                    const img = e.currentTarget;
                    if (img.dataset.fallback) return;
                    img.dataset.fallback = "1";
                    img.src = getAssetUrl("/images/pic/avatar.jpg");
                  }}
                  className="h-7 w-7 shrink-0 rounded-full bg-[var(--met-bg-elevated)] object-cover"
                />
                <span className="truncate text-sm text-[var(--met-fg)]">
                  {detail.creator?.nickname || "未知创建者"}
                </span>
                {detail.createTime ? (
                  <span className="shrink-0 text-xs text-[var(--met-fg-dim)]">
                    {getTimestampTime(detail.createTime)} 创建
                  </span>
                ) : null}
              </div>
            ) : null}
            {detail.description ? (
              <p
                className="line-clamp-2 text-sm text-[var(--met-fg-dim)]"
                title={detail.description}
              >
                {detail.description}
              </p>
            ) : null}
            <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-[var(--met-fg-dim)]">
              <span>共 {detail.trackCount ?? songs.length} 首歌曲</span>
              {detail.playCount ? (
                <span>播放 {formatNumber(detail.playCount)}</span>
              ) : null}
              {detail.updateTime ? (
                <span>{getTimestampTime(detail.updateTime)} 更新</span>
              ) : null}
            </div>
          </div>
        </div>
      )}

      {/* 超大歌单分片加载进度(对照旧「该歌单歌曲数量过多，请稍等」提示) */}
      {bigListProgress ? (
        <div className="mt-4 rounded-lg border border-[var(--met-border)] bg-[var(--met-bg-elevated)] px-4 py-2 text-center text-sm text-[var(--met-fg-dim)]">
          该歌单歌曲数量过多，请稍等… 已加载 {bigListProgress.loaded}/
          {bigListProgress.total} 首
        </div>
      ) : null}

      {/* 功能区:播放全部(房内禁用)+ 更多操作 + 模糊搜索(对照 Album.tsx 模式) */}
      {!songsQuery.isPending && songs.length ? (
        <div className="mt-5 flex items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <button
              type="button"
              disabled={isInRoom}
              title={isInRoom ? "一起听房间内暂不支持播放全部" : "播放全部"}
              onClick={() => void playAllSongs(songs, "normal")}
              className="flex items-center gap-1.5 rounded-full bg-[var(--met-primary)] px-4 py-1.5 text-sm font-medium text-[var(--met-bg)] transition-opacity hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-40"
            >
              <Play size={16} fill="currentColor" aria-hidden="true" />
              播放全部
            </button>
            <DropdownMenu
              items={moreOptions}
              align="start"
              ariaLabel="更多操作"
              title="更多操作"
              triggerClassName="flex h-9 w-9 items-center justify-center rounded-full border border-[var(--met-border)] text-[var(--met-fg)] transition-colors hover:bg-[var(--met-bg-hover)]"
            >
              <List size={16} aria-hidden="true" />
            </DropdownMenu>
            <span className="text-xs text-[var(--met-fg-dim)]">共 {songs.length} 首</span>
          </div>
          <input
            type="text"
            value={keyword}
            onChange={(e) => setKeyword(e.target.value)}
            placeholder="模糊搜索"
            className="h-9 w-36 rounded-full border border-[var(--met-border)] bg-transparent px-4 text-sm text-[var(--met-fg)] outline-none transition-all placeholder:text-[var(--met-fg-dim)] focus:w-52 focus:border-[var(--met-primary)]"
          />
        </div>
      ) : null}

      {/* 歌曲列表 */}
      <div className="mt-2">
        <SongList songs={songs} loading={songsQuery.isPending} filterKeyword={keyword} />
      </div>
    </div>
  );
}

// src/views/List/playlist.vue
<!-- 歌单页面 -->
<template>
  <div v-if="playlistId" class="playlist">
    <Transition name="fade" mode="out-in">
      <div v-if="playListDetail && Object.keys(playListDetail)?.length" class="detail">
        <div class="cover">
          <!-- 封面 -->
          <n-image
            :src="playListDetail.coverSize.l"
            :previewed-img-props="{ style: { borderRadius: '8px' } }"
            :preview-src="playListDetail.cover"
            class="cover-img"
            show-toolbar-tooltip
            @load="
              (e) => {
                e.target.style.opacity = 1;
              }
            "
          >
            <template #placeholder>
              <div class="cover-loading">
                <img class="loading-img" :src="getAssetUrl('/images/pic/song.jpg?assest')" alt="song" />
              </div>
            </template>
          </n-image>
          <!-- 封面背板 -->
          <n-image :src="playListDetail.coverSize.m" class="cover-shadow" preview-disabled />
        </div>
        <div class="data">
          <n-text class="name">
            {{
              userLikeData.playlists?.[0]?.id === playlistId
                ? "我喜欢的音乐"
                : playListDetail.name || "未知歌单"
            }}
          </n-text>
          <div class="creator">
            <n-avatar
              :src="
                (playListDetail.creator?.avatarUrl + '?param=300y$300').replace(/^http:/, 'https:')
              "
              :fallback-src="getAssetUrl('/images/pic/avatar.jpg?assest')"
              round
            />
            <n-text class="nickname">{{ playListDetail.creator?.nickname || "未知创建者" }}</n-text>
            <n-text v-if="playListDetail.createTime" class="create-time" depth="3">
              {{ getTimestampTime(playListDetail.createTime) }} 创建
            </n-text>
          </div>
          <!-- 标签 -->
          <n-flex v-if="playListDetail?.tags" class="tags">
            <n-tag
              v-for="(item, index) in playListDetail.tags"
              :key="index"
              :bordered="false"
              class="pl-tags"
              round
              @click="
                router.push({
                  path: '/discover/playlists',
                  query: { cat: item },
                })
              "
            >
              {{ item }}
            </n-tag>
          </n-flex>
          <!-- 数量 -->
          <n-flex class="num">
            <div v-if="playListDetail.count" class="num-item">
              <n-icon depth="3" size="18">
                <SvgIcon icon="music-note" />
              </n-icon>
              <n-text depth="3">{{ playListDetail.count }}</n-text>
            </div>
            <div v-if="playListDetail.playCount" class="num-item">
              <n-icon depth="3" size="18">
                <SvgIcon icon="headphones" />
              </n-icon>
              <n-text depth="3">{{ formatNumber(playListDetail?.playCount || 0) }}</n-text>
            </div>
            <div v-if="playListDetail.updateTime" class="num-item">
              <n-icon depth="3" size="18">
                <SvgIcon icon="update-rounded" />
              </n-icon>
              <n-text depth="3">{{ getTimestampTime(playListDetail.updateTime) }}</n-text>
            </div>
          </n-flex>
          <!-- 简介 -->
          <n-ellipsis
            v-if="playListDetail.description"
            :tooltip="false"
            class="description"
            expand-trigger="click"
            line-clamp="2"
          >
            <n-text depth="3">{{ playListDetail.description }}</n-text>
          </n-ellipsis>
          <n-text v-else class="description">太懒了吧，连简介都没写</n-text>
        </div>
      </div>
      <div v-else class="detail">
        <n-skeleton class="cover" />
        <div class="data">
          <n-skeleton :repeat="4" text />
        </div>
      </div>
    </Transition>
    <!-- 功能区 -->
    <Transition name="fade" mode="out-in">
      <n-flex :key="isUserPLayList" class="menu" justify="space-between">
        <n-flex class="left">
          <n-button
            :disabled="playListData === null || playListData === 'empty' || loadingMsg !== null || status.isInRoom"
            :focusable="false"
            type="primary"
            class="play"
            tag="div"
            circle
            strong
            secondary
            @click="playAllSongs(playListData)"
          >
            <template #icon>
              <n-icon size="32">
                <SvgIcon icon="play-arrow-rounded" />
              </n-icon>
            </template>
          </n-button>
          <n-dropdown :options="moreOptions" trigger="hover" placement="bottom-start">
            <n-button
              :focusable="false"
              class="more"
              size="large"
              tag="div"
              circle
              strong
              secondary
            >
              <template #icon>
                <n-icon>
                  <SvgIcon icon="format-list-bulleted" />
                </n-icon>
              </template>
            </n-button>
          </n-dropdown>
        </n-flex>
        <n-flex class="right">
          <!-- 模糊搜索 -->
          <Transition name="fade" mode="out-in">
            <n-input
              v-if="playListData !== 'empty' && playListData?.length"
              v-model:value="searchValue"
              :input-props="{ autoComplete: false }"
              class="search"
              placeholder="模糊搜索"
              clearable
              @input="localSearch"
            >
              <template #prefix>
                <n-icon size="18">
                  <SvgIcon icon="search-rounded" />
                </n-icon>
              </template>
            </n-input>
          </Transition>
        </n-flex>
      </n-flex>
    </Transition>
    <!-- 列表 -->
    <Transition name="fade" mode="out-in">
      <SongList v-if="!searchValue" :data="playListData" :sourceId="playlistId" />
      <SongList v-else-if="searchData?.length" :data="searchData" :sourceId="playlistId" />
      <n-empty
        v-else
        :description="`搜不到关于 ${searchValue} 的任何歌曲呀`"
        style="margin-top: 60px"
        size="large"
      >
        <template #icon>
          <n-icon>
            <SvgIcon icon="search-off" />
          </n-icon>
        </template>
      </n-empty>
    </Transition>
  </div>
  <div v-else class="title">
    <n-text class="key">参数不完整</n-text>
    <n-button :focusable="false" class="back" strong secondary @click="router.go(-1)">
      返回上一页
    </n-button>
  </div>
</template>

<script setup>
import { NIcon } from "naive-ui";
import { useRouter } from "vue-router";
import { storeToRefs } from "pinia";
import { siteData, siteStatus } from "@/stores";
import {
  getPlayListDetail,
  getAllPlayList,
} from "@/api/playlist";
import { formatNumber, fuzzySearch, getAssetUrl } from "@/utils/helper";
import { getTimestampTime } from "@/utils/timeTools";
import { playAllSongs } from "@/utils/Player";
import debounce from "@/utils/debounce";
import formatData from "@/utils/formatData";
import SvgIcon from "@/components/Global/SvgIcon";

const router = useRouter();
const data = siteData();
const status = siteStatus();
const { userLikeData } = storeToRefs(data);

// 歌单 ID
const playlistId = ref(
  router.currentRoute.value.name === "like-songs"
    ? userLikeData.value.playlists?.[0]?.id || null
    : router.currentRoute.value.query.id,
);

// 歌单数据
const loadingMsg = ref(null);
const isUserPLayList = ref(false);
const playListDetail = ref(null);
const playListData = ref(null);

// 模糊搜索数据
const searchValue = ref(null);
const searchData = ref([]);

// 图标渲染
const renderIcon = (icon) => {
  return () => h(NIcon, null, { default: () => h(SvgIcon, { icon }, null) });
};

// 更多操作数据
const moreOptions = ref([]);

// 更改更多操作数据
const changeMoreOptions = (detail) => {
  moreOptions.value = [
    {
      label: "打开源页面链接",
      key: "open",
      props: {
        onclick: () => {
          const id = playlistId.value;
          if (id) window.open(`https://y.qq.com/n/ryqq/playlist/${id}`);
        },
      },
      icon: renderIcon("link"),
    },
    {
      label: "打开经典播放器",
      key: "open",
      props: {
        onclick: () => {
          const id = playlistId.value;
          if (id) window.open(`/classic/player/?tid=${id}`);
        },
      },
      icon: renderIcon("play"),
    }
  ];
};

// 获取歌单信息
const getPlayListDetailData = async (id, justDetail = false) => {
  try {
    if (!id) return false;
    // 清空数据
    playListDetail.value = null;
    if (!justDetail) playListData.value = null;
    // 获取数据
    const detail = await getPlayListDetail(id);
    // 基础信息
    playListDetail.value = formatData(detail.playlist, "playlist", true)[0];
    // 更改更多操作数据
    changeMoreOptions(detail.playlist);
    // 是否终止
    if (justDetail) return true;
    // 是否为超大歌单
    if (detail.playlist.trackCount >= 800) {
      await getBigPlayListData(id, detail.playlist.trackCount);
      return true;
    }
    // 判断登录并获取歌曲
    let songsDetail = null;
    const limit = detail.playlist.trackCount || 0;
    songsDetail = await getAllPlayList(id, limit);
    // 写入歌单数据
    if (!songsDetail.songs) {
      playListData.value = "error";
    } else {
      playListData.value = formatData(songsDetail.songs, "song");
    }
  } catch (error) {
    console.error("获取歌单信息出错：", error);
    $message.error("获取歌单信息出错");
  }
};

// 获取超大歌单数据
const getBigPlayListData = async (id, count) => {
  console.log(id, count);
  loadingMsg.value = $message.loading("该歌单歌曲数量过多，请稍等", {
    duration: 0,
  });
  // 循环获取
  let offset = 0;
  playListData.value = [];
  while ((count === null || offset < count) && loadingMsg.value) {
    const songsDetail = await getAllPlayList(id, 800, offset);
    const albumsData = formatData(songsDetail.songs, "song");
    playListData.value = playListData.value.concat(albumsData);
    offset += 800;
  }
  // 关闭加载提示
  loadingMsg.value?.destroy();
  loadingMsg.value = null;
};

// 歌曲模糊搜索
const localSearch = debounce((val) => {
  const searchValue = val?.trim();
  // 是否为空
  if (!searchValue || searchValue === "") {
    return true;
  }
  // 返回结果
  const result = fuzzySearch(searchValue, playListData.value);
  searchData.value = result;
}, 300);


// 监听路由变化
watch(
  () => router.currentRoute.value,
  async (val) => {
    if (val.name === "playlist" || val.name === "like-songs") {
      playlistId.value =
        router.currentRoute.value.name === "like-songs"
          ? userLikeData.value.playlists?.[0]?.id || null
          : val.query?.id;
      await getPlayListDetailData(playlistId.value);
    }
  },
);

onBeforeMount(async () => {
  await getPlayListDetailData(playlistId.value);
});

onBeforeUnmount(() => {
  loadingMsg.value?.destroy();
  loadingMsg.value = null;
});
</script>

<style lang="scss" scoped>
.playlist {
  .detail {
    display: flex;
    flex-direction: row;
    align-items: stretch;
    margin-bottom: 20px;
    .cover {
      position: relative;
      display: flex;
      width: 200px;
      height: 200px;
      min-width: 200px;
      margin-right: 20px;
      border-radius: 8px;
      .cover-img {
        width: 100%;
        height: 100%;
        border-radius: 8px;
        z-index: 1;
        transition:
          filter 0.3s,
          transform 0.3s;
        :deep(img) {
          width: 100%;
          opacity: 0;
          transition: opacity 0.35s ease-in-out;
        }
        &:active {
          transform: scale(0.98);
        }
      }
      .cover-shadow {
        position: absolute;
        top: 4px;
        height: 100%;
        width: 100%;
        filter: blur(16px) opacity(0.6);
        transform: scale(0.92, 0.96);
        z-index: 0;
        background-size: cover;
        aspect-ratio: 1/1;
      }
    }
    .data {
      width: 100%;
      .name {
        font-size: 30px;
        font-weight: bold;
        margin-bottom: 12px;
        -webkit-line-clamp: 2;
      }
      .creator {
        display: flex;
        flex-direction: row;
        align-items: center;
        .n-avatar {
          width: 28px;
          height: 28px;
          margin-right: 8px;
        }
        .nickname {
          transition: color 0.3s;
          cursor: pointer;
          &:hover {
            color: var(--main-color);
          }
        }
        .create-time {
          margin-left: 12px;
          font-size: 13px;
        }
      }
      .tags {
        margin-top: 12px;
        .pl-tags {
          font-size: 13px;
          padding: 0 16px;
          line-height: 0;
          cursor: pointer;
          transition:
            transform 0.3s,
            background-color 0.3s,
            color 0.3s;
          &:hover {
            background-color: var(--main-second-color);
            color: var(--main-color);
          }
          &:active {
            transform: scale(0.95);
          }
        }
      }
      .num {
        margin-top: 12px;
        .num-item {
          display: flex;
          flex-direction: row;
          align-items: center;
          .n-icon {
            margin-right: 4px;
            // color: var(--main-color);
          }
        }
      }
      .description {
        margin-top: 12px;
        margin-left: 2px;
        .n-text {
          display: initial;
        }
      }
      :deep(.n-skeleton) {
        &:first-child {
          width: 60%;
          margin-top: 0;
          height: 40px;
        }
        height: 30px;
        margin-top: 12px;
        border-radius: 8px;
      }
    }
  }
  .menu {
    flex-wrap: nowrap;
    align-items: center;
    margin: 26px 0;
    .left {
      flex-wrap: nowrap;
      align-items: center;
      .play {
        --n-width: 46px;
        --n-height: 46px;
      }
    }
    .right {
      .search {
        height: 40px;
        width: 130px;
        display: flex;
        align-items: center;
        border-radius: 40px;
        transition:
          width 0.3s,
          background-color 0.3s;
        &.n-input--focus {
          width: 200px;
        }
      }
    }
  }

  @media (max-width: 700px) {
    .detail {
      .cover {
        width: 140px;
        height: 140px;
        min-width: 140px;
      }
      .data {
        .name {
          font-size: 20px;
          margin-bottom: 4px;
        }
        .creator {
          .n-avatar {
            width: 20px;
            height: 20px;
            margin-right: 6px;
          }
          .nickname {
            font-size: 12px;
          }
          .create-time {
            margin-left: 6px;
            font-size: 12px;
          }
        }
        .tags {
          .pl-tags {
            font-size: 12px;
            padding: 0 12px;
          }
        }
        .num,
        .description {
          display: none !important;
        }
      }
    }
    .menu {
      margin: 20px 0;
      .left {
        .play {
          --n-width: 40px;
          --n-height: 40px;
          .n-icon {
            font-size: 22px !important;
          }
        }
        .like {
          --n-height: 36px;
          --n-font-size: 13px;
          --n-padding: 0 16px;
          --n-icon-size: 18px;
          :deep(.n-button__icon) {
            margin: 0;
          }
          :deep(.n-button__content) {
            display: none;
          }
        }
        .more {
          --n-height: 36px;
          --n-font-size: 13px;
          --n-icon-size: 18px;
        }
      }
      .right {
        .search {
          height: 36px;
          width: 130px;
          font-size: 13px;
        }
      }
    }
  }
}
.title {
  display: flex;
  flex-direction: column;
  .key {
    margin: 10px 0;
    font-size: 36px;
    font-weight: bold;
    margin-right: 8px;
  }
  .back {
    width: 98px;
  }
}
</style>
